language: python
env: # These should match the tox env list
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install: pip install tox coveralls
script: tox
sudo: false
after_success:
    coveralls
