name: Type validation

on:
 push:
   branches: [master]
   tags:
 pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: python -m pip install tox

    - name: Run ${{ matrix.python-version }} mypy
      run: tox -e mypy
